// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../src/_generated/api.js";


export const api = {
  func: {
    todos: {
      add: createApiLeaf<"mutation", typeof import("../src/func/todos").add>(convexApi["func"]["todos"]["add"], { auth: "required", type: "mutation" }),
      list: createApiLeaf<"query", typeof import("../src/func/todos").list>(convexApi["func"]["todos"]["list"], { auth: "required", type: "query" }),
      remove: createApiLeaf<"mutation", typeof import("../src/func/todos").remove>(convexApi["func"]["todos"]["remove"], { auth: "required", type: "mutation" }),
      toggle: createApiLeaf<"mutation", typeof import("../src/func/todos").toggle>(convexApi["func"]["todos"]["toggle"], { auth: "required", type: "mutation" }),
    },
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

