// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
	todos: {
		add: { auth: "required", type: "mutation" },
		list: { auth: "required", type: "query" },
		remove: { auth: "required", type: "mutation" },
		toggle: { auth: "required", type: "mutation" },
	},
	_http: {},
} as const;

export type Meta = typeof meta;
