[env]
TURBO_TELEMETRY_DISABLED = "1"
DO_NOT_TRACK = "1"

[tools]
bun = "latest"
node = "latest"
graphite = "latest"
github-cli = "latest"
"npm:turbo" = "latest"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"

[hooks]
preinstall = '''
  command -v node &> /dev/null || echo "Node.js is not installed. Please install Node.js to continue." && exit 1
'''
postinstall = '''
  bun pm pkg set packageManager=bun@$(bun --version) && test -d node_modules || bun install
'''

[tasks.docker]
description = "Build and start the Docker container"
run = "cd docker && docker compose --env-file ../.env.local -f compose.dev.yaml up -d --build"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"
