[env]
TURBO_TELEMETRY_DISABLED = "1"
DO_NOT_TRACK = "1"

[tools]
node = "latest"
bun = "latest"
github-cli = "latest"
"npm:turbo" = "latest"

[hooks]
postinstall = '''
  bun pm pkg set packageManager=bun@$(bun --version) && test -d node_modules || bun install
'''

[tasks.docker]
description = "Build and start the Docker container"
dir = "docker"
run = "docker compose --env-file ../.env.local -f compose.dev.yaml up -d --build"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"
