/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTanstackFormRouteImport } from './routes/demo/tanstack-form'
import { Route as DemoShadcnRouteImport } from './routes/demo/shadcn'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDemoConvexRouteImport } from './routes/_authenticated/demo/convex'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackFormRoute = DemoTanstackFormRouteImport.update({
  id: '/demo/tanstack-form',
  path: '/demo/tanstack-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoShadcnRoute = DemoShadcnRouteImport.update({
  id: '/demo/shadcn',
  path: '/demo/shadcn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoConvexRoute = AuthenticatedDemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo/shadcn': typeof DemoShadcnRoute
  '/demo/tanstack-form': typeof DemoTanstackFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/convex': typeof AuthenticatedDemoConvexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo/shadcn': typeof DemoShadcnRoute
  '/demo/tanstack-form': typeof DemoTanstackFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/convex': typeof AuthenticatedDemoConvexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo/shadcn': typeof DemoShadcnRoute
  '/demo/tanstack-form': typeof DemoTanstackFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/demo/convex': typeof AuthenticatedDemoConvexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo/shadcn'
    | '/demo/tanstack-form'
    | '/demo/tanstack-query'
    | '/demo/convex'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo/shadcn'
    | '/demo/tanstack-form'
    | '/demo/tanstack-query'
    | '/demo/convex'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo/shadcn'
    | '/demo/tanstack-form'
    | '/demo/tanstack-query'
    | '/_authenticated/demo/convex'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoShadcnRoute: typeof DemoShadcnRoute
  DemoTanstackFormRoute: typeof DemoTanstackFormRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-form': {
      id: '/demo/tanstack-form'
      path: '/demo/tanstack-form'
      fullPath: '/demo/tanstack-form'
      preLoaderRoute: typeof DemoTanstackFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/shadcn': {
      id: '/demo/shadcn'
      path: '/demo/shadcn'
      fullPath: '/demo/shadcn'
      preLoaderRoute: typeof DemoShadcnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo/convex': {
      id: '/_authenticated/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof AuthenticatedDemoConvexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDemoConvexRoute: typeof AuthenticatedDemoConvexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDemoConvexRoute: AuthenticatedDemoConvexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoShadcnRoute: DemoShadcnRoute,
  DemoTanstackFormRoute: DemoTanstackFormRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
