/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppAuthenticatedRouteImport } from './routes/_app/_authenticated'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDemoTanstackFormRouteImport } from './routes/_app/demo/tanstack-form'
import { Route as AppDemoShadcnRouteImport } from './routes/_app/demo/shadcn'
import { Route as AppAuthenticatedDemoFileUploadRouteImport } from './routes/_app/_authenticated/demo/file-upload'
import { Route as AppAuthenticatedDemoConvexOptimisticRouteImport } from './routes/_app/_authenticated/demo/convex-optimistic'
import { Route as AppAuthenticatedDemoConvexRouteImport } from './routes/_app/_authenticated/demo/convex'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRoute,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemoTanstackFormRoute = AppDemoTanstackFormRouteImport.update({
  id: '/demo/tanstack-form',
  path: '/demo/tanstack-form',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoShadcnRoute = AppDemoShadcnRouteImport.update({
  id: '/demo/shadcn',
  path: '/demo/shadcn',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthenticatedDemoFileUploadRoute =
  AppAuthenticatedDemoFileUploadRouteImport.update({
    id: '/demo/file-upload',
    path: '/demo/file-upload',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedDemoConvexOptimisticRoute =
  AppAuthenticatedDemoConvexOptimisticRouteImport.update({
    id: '/demo/convex-optimistic',
    path: '/demo/convex-optimistic',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedDemoConvexRoute =
  AppAuthenticatedDemoConvexRouteImport.update({
    id: '/demo/convex',
    path: '/demo/convex',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/demo/shadcn': typeof AppDemoShadcnRoute
  '/demo/tanstack-form': typeof AppDemoTanstackFormRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/demo/convex': typeof AppAuthenticatedDemoConvexRoute
  '/demo/convex-optimistic': typeof AppAuthenticatedDemoConvexOptimisticRoute
  '/demo/file-upload': typeof AppAuthenticatedDemoFileUploadRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/': typeof AppIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/demo/shadcn': typeof AppDemoShadcnRoute
  '/demo/tanstack-form': typeof AppDemoTanstackFormRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/demo/convex': typeof AppAuthenticatedDemoConvexRoute
  '/demo/convex-optimistic': typeof AppAuthenticatedDemoConvexOptimisticRoute
  '/demo/file-upload': typeof AppAuthenticatedDemoFileUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/demo/shadcn': typeof AppDemoShadcnRoute
  '/_app/demo/tanstack-form': typeof AppDemoTanstackFormRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/_app/_authenticated/demo/convex': typeof AppAuthenticatedDemoConvexRoute
  '/_app/_authenticated/demo/convex-optimistic': typeof AppAuthenticatedDemoConvexOptimisticRoute
  '/_app/_authenticated/demo/file-upload': typeof AppAuthenticatedDemoFileUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/demo/shadcn'
    | '/demo/tanstack-form'
    | '/api/auth/$'
    | '/api/files/$'
    | '/demo/convex'
    | '/demo/convex-optimistic'
    | '/demo/file-upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/demo/shadcn'
    | '/demo/tanstack-form'
    | '/api/auth/$'
    | '/api/files/$'
    | '/demo/convex'
    | '/demo/convex-optimistic'
    | '/demo/file-upload'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/_authenticated'
    | '/auth/login'
    | '/auth/signup'
    | '/_app/'
    | '/_app/demo/shadcn'
    | '/_app/demo/tanstack-form'
    | '/api/auth/$'
    | '/api/files/$'
    | '/_app/_authenticated/demo/convex'
    | '/_app/_authenticated/demo/convex-optimistic'
    | '/_app/_authenticated/demo/file-upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/demo/tanstack-form': {
      id: '/_app/demo/tanstack-form'
      path: '/demo/tanstack-form'
      fullPath: '/demo/tanstack-form'
      preLoaderRoute: typeof AppDemoTanstackFormRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/shadcn': {
      id: '/_app/demo/shadcn'
      path: '/demo/shadcn'
      fullPath: '/demo/shadcn'
      preLoaderRoute: typeof AppDemoShadcnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authenticated/demo/file-upload': {
      id: '/_app/_authenticated/demo/file-upload'
      path: '/demo/file-upload'
      fullPath: '/demo/file-upload'
      preLoaderRoute: typeof AppAuthenticatedDemoFileUploadRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_authenticated/demo/convex-optimistic': {
      id: '/_app/_authenticated/demo/convex-optimistic'
      path: '/demo/convex-optimistic'
      fullPath: '/demo/convex-optimistic'
      preLoaderRoute: typeof AppAuthenticatedDemoConvexOptimisticRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_app/_authenticated/demo/convex': {
      id: '/_app/_authenticated/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof AppAuthenticatedDemoConvexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedDemoConvexRoute: typeof AppAuthenticatedDemoConvexRoute
  AppAuthenticatedDemoConvexOptimisticRoute: typeof AppAuthenticatedDemoConvexOptimisticRoute
  AppAuthenticatedDemoFileUploadRoute: typeof AppAuthenticatedDemoFileUploadRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedDemoConvexRoute: AppAuthenticatedDemoConvexRoute,
  AppAuthenticatedDemoConvexOptimisticRoute:
    AppAuthenticatedDemoConvexOptimisticRoute,
  AppAuthenticatedDemoFileUploadRoute: AppAuthenticatedDemoFileUploadRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

interface AppRouteChildren {
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDemoShadcnRoute: typeof AppDemoShadcnRoute
  AppDemoTanstackFormRoute: typeof AppDemoTanstackFormRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDemoShadcnRoute: AppDemoShadcnRoute,
  AppDemoTanstackFormRoute: AppDemoTanstackFormRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
