// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../src/_generated/api.js";


export const api = {
  func: {
    files: {
      generateUploadUrl: createApiLeaf<"mutation", typeof import("../src/func/files").generateUploadUrl>(convexApi["func"]["files"]["generateUploadUrl"], { auth: "required", type: "mutation" }),
      list: createApiLeaf<"query", typeof import("../src/func/files").list>(convexApi["func"]["files"]["list"], { auth: "required", type: "query" }),
      remove: createApiLeaf<"mutation", typeof import("../src/func/files").remove>(convexApi["func"]["files"]["remove"], { auth: "required", type: "mutation" }),
      saveFile: createApiLeaf<"mutation", typeof import("../src/func/files").saveFile>(convexApi["func"]["files"]["saveFile"], { auth: "required", type: "mutation" }),
    },
    paginationDemo: {
      list: createApiLeaf<"query", typeof import("../src/func/paginationDemo").list>(convexApi["func"]["paginationDemo"]["list"], { auth: "required", limit: 40, type: "query" }),
    },
    session: {
      me: createApiLeaf<"query", typeof import("../src/func/session").me>(convexApi["func"]["session"]["me"], { type: "query" }),
    },
    todos: {
      add: createApiLeaf<"mutation", typeof import("../src/func/todos").add>(convexApi["func"]["todos"]["add"], { auth: "required", type: "mutation" }),
      list: createApiLeaf<"query", typeof import("../src/func/todos").list>(convexApi["func"]["todos"]["list"], { auth: "required", type: "query" }),
      remove: createApiLeaf<"mutation", typeof import("../src/func/todos").remove>(convexApi["func"]["todos"]["remove"], { auth: "required", type: "mutation" }),
      toggle: createApiLeaf<"mutation", typeof import("../src/func/todos").toggle>(convexApi["func"]["todos"]["toggle"], { auth: "required", type: "mutation" }),
    },
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

