/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDemoTanstackOptimisticRouteImport } from './routes/_authenticated/demo/tanstack-optimistic'
import { Route as AuthenticatedDemoTableRouteImport } from './routes/_authenticated/demo/table'
import { Route as AuthenticatedDemoMassiveDataRouteImport } from './routes/_authenticated/demo/massive-data'
import { Route as AuthenticatedDemoFileUploadRouteImport } from './routes/_authenticated/demo/file-upload'
import { Route as AuthenticatedDemoConvexQueryRouteImport } from './routes/_authenticated/demo/convex-query'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedDemoFormAddressRouteImport } from './routes/_authenticated/demo/form.address'
import { Route as AuthenticatedAdminPermissionsAdminRouteImport } from './routes/_authenticated/admin/permissions.admin'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoTanstackOptimisticRoute =
  AuthenticatedDemoTanstackOptimisticRouteImport.update({
    id: '/demo/tanstack-optimistic',
    path: '/demo/tanstack-optimistic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoTableRoute = AuthenticatedDemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoMassiveDataRoute =
  AuthenticatedDemoMassiveDataRouteImport.update({
    id: '/demo/massive-data',
    path: '/demo/massive-data',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoFileUploadRoute =
  AuthenticatedDemoFileUploadRouteImport.update({
    id: '/demo/file-upload',
    path: '/demo/file-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoConvexQueryRoute =
  AuthenticatedDemoConvexQueryRouteImport.update({
    id: '/demo/convex-query',
    path: '/demo/convex-query',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoFormAddressRoute =
  AuthenticatedDemoFormAddressRouteImport.update({
    id: '/demo/form/address',
    path: '/demo/form/address',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermissionsAdminRoute =
  AuthenticatedAdminPermissionsAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedAdminPermissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/demo/convex-query': typeof AuthenticatedDemoConvexQueryRoute
  '/demo/file-upload': typeof AuthenticatedDemoFileUploadRoute
  '/demo/massive-data': typeof AuthenticatedDemoMassiveDataRoute
  '/demo/table': typeof AuthenticatedDemoTableRoute
  '/demo/tanstack-optimistic': typeof AuthenticatedDemoTanstackOptimisticRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/permissions/admin': typeof AuthenticatedAdminPermissionsAdminRoute
  '/demo/form/address': typeof AuthenticatedDemoFormAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/demo/convex-query': typeof AuthenticatedDemoConvexQueryRoute
  '/demo/file-upload': typeof AuthenticatedDemoFileUploadRoute
  '/demo/massive-data': typeof AuthenticatedDemoMassiveDataRoute
  '/demo/table': typeof AuthenticatedDemoTableRoute
  '/demo/tanstack-optimistic': typeof AuthenticatedDemoTanstackOptimisticRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/permissions/admin': typeof AuthenticatedAdminPermissionsAdminRoute
  '/demo/form/address': typeof AuthenticatedDemoFormAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/demo/convex-query': typeof AuthenticatedDemoConvexQueryRoute
  '/_authenticated/demo/file-upload': typeof AuthenticatedDemoFileUploadRoute
  '/_authenticated/demo/massive-data': typeof AuthenticatedDemoMassiveDataRoute
  '/_authenticated/demo/table': typeof AuthenticatedDemoTableRoute
  '/_authenticated/demo/tanstack-optimistic': typeof AuthenticatedDemoTanstackOptimisticRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/admin/permissions/admin': typeof AuthenticatedAdminPermissionsAdminRoute
  '/_authenticated/demo/form/address': typeof AuthenticatedDemoFormAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/auth/login'
    | '/admin/permissions'
    | '/admin/users'
    | '/demo/convex-query'
    | '/demo/file-upload'
    | '/demo/massive-data'
    | '/demo/table'
    | '/demo/tanstack-optimistic'
    | '/api/auth/$'
    | '/admin/permissions/admin'
    | '/demo/form/address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/auth/login'
    | '/admin/permissions'
    | '/admin/users'
    | '/demo/convex-query'
    | '/demo/file-upload'
    | '/demo/massive-data'
    | '/demo/table'
    | '/demo/tanstack-optimistic'
    | '/api/auth/$'
    | '/admin/permissions/admin'
    | '/demo/form/address'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forbidden'
    | '/auth/login'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/users'
    | '/_authenticated/demo/convex-query'
    | '/_authenticated/demo/file-upload'
    | '/_authenticated/demo/massive-data'
    | '/_authenticated/demo/table'
    | '/_authenticated/demo/tanstack-optimistic'
    | '/api/auth/$'
    | '/_authenticated/admin/permissions/admin'
    | '/_authenticated/demo/form/address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo/tanstack-optimistic': {
      id: '/_authenticated/demo/tanstack-optimistic'
      path: '/demo/tanstack-optimistic'
      fullPath: '/demo/tanstack-optimistic'
      preLoaderRoute: typeof AuthenticatedDemoTanstackOptimisticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/table': {
      id: '/_authenticated/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof AuthenticatedDemoTableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/massive-data': {
      id: '/_authenticated/demo/massive-data'
      path: '/demo/massive-data'
      fullPath: '/demo/massive-data'
      preLoaderRoute: typeof AuthenticatedDemoMassiveDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/file-upload': {
      id: '/_authenticated/demo/file-upload'
      path: '/demo/file-upload'
      fullPath: '/demo/file-upload'
      preLoaderRoute: typeof AuthenticatedDemoFileUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/convex-query': {
      id: '/_authenticated/demo/convex-query'
      path: '/demo/convex-query'
      fullPath: '/demo/convex-query'
      preLoaderRoute: typeof AuthenticatedDemoConvexQueryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/form/address': {
      id: '/_authenticated/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof AuthenticatedDemoFormAddressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions/admin': {
      id: '/_authenticated/admin/permissions/admin'
      path: '/admin'
      fullPath: '/admin/permissions/admin'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsAdminRouteImport
      parentRoute: typeof AuthenticatedAdminPermissionsRoute
    }
  }
}

interface AuthenticatedAdminPermissionsRouteChildren {
  AuthenticatedAdminPermissionsAdminRoute: typeof AuthenticatedAdminPermissionsAdminRoute
}

const AuthenticatedAdminPermissionsRouteChildren: AuthenticatedAdminPermissionsRouteChildren =
  {
    AuthenticatedAdminPermissionsAdminRoute:
      AuthenticatedAdminPermissionsAdminRoute,
  }

const AuthenticatedAdminPermissionsRouteWithChildren =
  AuthenticatedAdminPermissionsRoute._addFileChildren(
    AuthenticatedAdminPermissionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDemoConvexQueryRoute: typeof AuthenticatedDemoConvexQueryRoute
  AuthenticatedDemoFileUploadRoute: typeof AuthenticatedDemoFileUploadRoute
  AuthenticatedDemoMassiveDataRoute: typeof AuthenticatedDemoMassiveDataRoute
  AuthenticatedDemoTableRoute: typeof AuthenticatedDemoTableRoute
  AuthenticatedDemoTanstackOptimisticRoute: typeof AuthenticatedDemoTanstackOptimisticRoute
  AuthenticatedDemoFormAddressRoute: typeof AuthenticatedDemoFormAddressRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminPermissionsRoute:
    AuthenticatedAdminPermissionsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDemoConvexQueryRoute: AuthenticatedDemoConvexQueryRoute,
  AuthenticatedDemoFileUploadRoute: AuthenticatedDemoFileUploadRoute,
  AuthenticatedDemoMassiveDataRoute: AuthenticatedDemoMassiveDataRoute,
  AuthenticatedDemoTableRoute: AuthenticatedDemoTableRoute,
  AuthenticatedDemoTanstackOptimisticRoute:
    AuthenticatedDemoTanstackOptimisticRoute,
  AuthenticatedDemoFormAddressRoute: AuthenticatedDemoFormAddressRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
